# Generated by Django 4.1 on 2022-09-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
