# Generated by Django 4.1 on 2022-09-14 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
                ('brand_slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('brand_image', models.ImageField(blank=True, upload_to='photos/brand')),
                ('offer_status', models.BooleanField(default=False)),
            ],
        ),
    ]
