# Generated by Django 4.1 on 2022-09-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brands_brand_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='brand_slug',
            new_name='slug',
        ),
    ]
